### ISSUE TITLE
Issue 1: Add Addition function

### ISSUE THREAD

**Issue by joseph-allen** [joezcool02/OurCalculator#1]
we need a function which takes two integers and returns the sum of those two numbers!

make sure when you push the code you commit with the message OC-1 for this. make sure you open a PR to close this :)

**Comment by JornPrengerFormeel** [comment]
o, sorry. didnt look at this first. what is an oc-1 and what is a PR(i think pull request)

**Comment by joseph-allen** [comment]
no problem, OC-1 is something I would like you to put in your commit message, When you push something to this repository you give it a message when you type git commit
`git commit -m "Your message foes here"`

so for example if you do this task

`git commit -m "OC-1 Add Function"`

PR is indeed Pull Request :)

**Comment by joseph-allen** [comment]
@jorn600 is working on this one!

**Comment by joseph-allen** [comment]
@jorn600 see [This PR](https://github.com/joezcool02/OurCalculator/pull/5/files)

that is one way of doing this. if you don't understand what it is doing let me know and I will try to help.

**Comment by JornPrengerFormeel** [comment]
o haha, dient see that one
 
i understand now

**Comment by JornPrengerFormeel** [comment]
i will close my pull request

**Comment by joseph-allen** [comment]
resolved
