### ISSUE TITLE
Issue 5: Button Class

### ISSUE THREAD

**Issue by joseph-allen** [joezcool02/OurCalculator#10]
We need a generic Button Class which will pass two numbers to a function when clicked.

How you define this button class is up to you.

should we be able to pass the location of the button to the button class too? The Size? Or is this not necessary since all the buttons will be the same size?

Is there a way we can write this button in a clever way so we can use it for number buttons too?

**Comment by Floempie** [comment]
I think its best to keep them the same size. But use different colours for numbers and operators. 
Maybe even a function in the button that detects if its a number or an operator?

The next question is: How do we decide where to place the buttons?
We could code a grid of buttons, but which button goes where and how to code this the best way?
Maybe use a numbering system: each time we pass the row and col to the button class so it knows where to draw in a grid.

**Comment by JornPrengerFormeel** [comment]
make a grid of for loops like this:

for(int i = 0; i <= width; i = i + 10)
{
     line(0,0,i,height);
}

**Comment by JornPrengerFormeel** [comment]
then you can easily count where to place it, instead of guessing

**Comment by joseph-allen** [comment]
These issues don't need to be solved yet we just need a very generic class :)

**Comment by Floempie** [comment]
What about commenting the code so everyone can read and learn from it??

**Comment by joseph-allen** [comment]
a good practice is writing code in such a way that it is obvious what it does anyway with good function naming and varaible names. However comment all you like, I won't ask for comments or no comments :)

**Comment by JornPrengerFormeel** [comment]
What a shame there is no button() just like a rect function. They should add that.

**Comment by joseph-allen** [comment]
it would be considered clutter I would imagine, most projects dont need buttons. There are libraries you can import tht already have them but writing our own is  a good exercise

**Comment by joseph-allen** [comment]
done!
