### ISSUE TITLE
input variable

### ISSUE THREAD

**Issue by JornPrengerFormeel** [joezcool02/OurCalculator#11]
what is a good way of getting a keyboard input into a variable?

**Comment by joseph-allen** [comment]
[Here](https://processing.org/examples/keyboard.html)
, is this a duplicated of https://github.com/joezcool02/OurCalculator/issues/9 though?

using keyboard for input would be a good way to start so we can test the operators

**Comment by joseph-allen** [comment]
closing this as not an isolated piece of work
