### ISSUE TITLE
Issue 6: Button class to take a string

### ISSUE THREAD

**Issue by joseph-allen** [joezcool02/OurCalculator#13]
The Button Class needs to be updated to take a string on construction and to display that string in the center of itself.

**Comment by JornPrengerFormeel** [comment]
Cant we Just display a text() over the block that is going to be the button

**Comment by Floempie** [comment]
Something along the way of: 
If mousePressed within the boundaries of the button.
Do something.

Inside the button class.

**Comment by joseph-allen** [comment]
we can do, but this text has to be tied with the Button itself :) and we need the correct position of the text!

if you work on this make sure you say so here

**Comment by JornPrengerFormeel** [comment]
Cant work today anymore, maybe tonight

**Comment by joseph-allen** [comment]
no problem, this is a hobby project :)

**Comment by hschallh** [comment]
On it!
