### ISSUE TITLE
Issue 7: Detect Button Click

### ISSUE THREAD

**Issue by joseph-allen** [joezcool02/OurCalculator#14]
we need to detect when a Button is clicked, then call a function if it is clicked.

**Comment by GideonBuckwalter** [comment]
I can work on this!

**Comment by GideonBuckwalter** [comment]
Hey @joezcool02 , I know you told someone else to prefix their commit message with OC-1. For Issue 7, should I prefix mine with OC-7?

**Comment by joseph-allen** [comment]
that is the general plan, if you forget to I change them when we squash and merge anyway :)
