### ISSUE TITLE
Issue 8: Button performs a function when  pressed

### ISSUE THREAD

**Issue by joseph-allen** [joezcool02/OurCalculator#17]
not sure if this should take a generic function or not? we could pass the function as a parameter? Or am I thinking in Javascript :P

**Comment by GideonBuckwalter** [comment]
Yeah, I haven't been able to get Processing to play nice with Java 8 function parameters :( What do you think about making something like a `ButtonAction` interface with a `performAction` method? Then each button could store an instance of an implementing class whose `performAction` method would be called whenever the button is clicked. I think it might be hard to carry along state from other parts of the program though...

**Comment by joseph-allen** [comment]
I guess just pass it a string that is the operator or operand and we can call it from within.

I would imagine in the future we will have global stores of the numbers anyway so all we need is the operator to be passed just as a sting will do '+', '*' or '=' ?

**Comment by GideonBuckwalter** [comment]
Ok, that seems simpler.

**Comment by GideonBuckwalter** [comment]
I'll start working on this.
