### ISSUE TITLE
Issue 9: Create Basic Button Layout

### ISSUE THREAD

**Issue by GideonBuckwalter** [joezcool02/OurCalculator#19]
I think once @hschallh's pull request (#18) is approved, someone should create a bunch of `Button` instances (maybe stored in a list) to give us a working layout for the calculator. That way we can more easily test code while we're writing it.

**Comment by joseph-allen** [comment]
shall we agree just the numbers 0-9 and a +,x and = button for now?

**Comment by hschallh** [comment]
Might as well add a - and / button in there.

**Comment by Praetrorian** [comment]
Let's do a roman number calculator \o/

**Comment by joseph-allen** [comment]
@Praetrorian that is a completely different project itself :P I will put it under "Maybe Later"

**Comment by JornPrengerFormeel** [comment]
heck, why don't we make it a duodecimal calculator!

**Comment by JornPrengerFormeel** [comment]
working on this!

**Comment by JornPrengerFormeel** [comment]
Should we do this with arrays?

**Comment by joseph-allen** [comment]
we will get the basics done first and then move up if we all want to :)

This ticket is just to make the buttons so will probably just be like 10 lines of creating button objects and invoking their display methods.

**Comment by JornPrengerFormeel** [comment]
how to i create a button object?
and what is a display method?

**Comment by JornPrengerFormeel** [comment]
i dont know how to create a button layout using the button class, can someone help?

**Comment by hschallh** [comment]
[This](https://www.tutorialspoint.com/java/java_object_classes.htm) will be a good place to start with objects and classes.  Our button class is defined in Button.pde, so to create a new object, you'd need to do something like `Button oneButton = new Button(xpos, ypos, "1")`.  You can call `oneButton`'s display method with `oneButton.display()`.

**Comment by joseph-allen** [comment]
great advice @hschallh , @jorn600 I think you should take this one so you can learn how to create and invoke classes :)

**Comment by ayush-seth** [comment]
I am willing to implement this, perhaps we could use a library for the GUI buttons, like [controlP5](https://github.com/sojamo/controlp5). It makes it really easy.

**Comment by JornPrengerFormeel** [comment]
Oké, could i do that. I was working on it before

**Comment by joseph-allen** [comment]
We already have a button class since it is a good open source excercise anyway :) @jorn600 you are already doing this with your PR anyway
