### ISSUE TITLE
Issue 10: Subtract function request

### ISSUE THREAD

**Issue by hschallh** [joezcool02/OurCalculator#20]
I'd like to use this calculator to prove to my SO just how much money they subtract from my monthly paycheck. Would love to see a subtract button in a future release.

**Comment by joseph-allen** [comment]
@hschallh I was not expecting to read that!

**Comment by JimmySticks2001** [comment]
I can totes do this!

**Comment by JimmySticks2001** [comment]
#22 I think I did this right.

**Comment by JimmySticks2001** [comment]
This can be closed as #22 was merged into the master branch.
