### ISSUE TITLE
Issue 11: Divide function request

### ISSUE THREAD

**Issue by hschallh** [joezcool02/OurCalculator#21]
Wish I could use this calculator to show my SO how much "half" of my hamburger really is. Could we get a divide function too?

**Comment by GideonBuckwalter** [comment]
What is a `hamburger`? Is that some new Java 9 datatype? I don't know if we ought to support operations on arbitrarily chosen classes.

**Comment by hschallh** [comment]
You're probably right. I guess a function that handles two floats would suffice.

**Comment by joseph-allen** [comment]
make sure whoever does this handles dividing by zero in a way we expect

**Comment by JornPrengerFormeel** [comment]
well if we divide by zero the whole program just screams error everywhere and then the world explodes.

**Comment by JornPrengerFormeel** [comment]
i did this

**Comment by WookiefromNZ** [comment]
I wasn't sure how to approach the divide by 0 so I only allowed it to return a value when the denominator is NOT 0, else it throws a 'cannot divide by zero' exception, this works for int and float of 0 and 0.0 respectively.
