### ISSUE TITLE
Issue 12: remove unnecessary comments

### ISSUE THREAD

**Issue by joseph-allen** [joezcool02/OurCalculator#24]
we can get rid of the lines like "TASK 10 ----------------------------------------------------------"

feel free to replace them with something short and meaningful if you think it is necessary

**Comment by JimmySticks2001** [comment]
I was thinking of cleaning up the comments when I pushed my subtract function but didn't want to step on any toes. Back in my day I was taught to use comments before and after to describe what a function did. Example:
//Takes in two floats, a and b. Returns the float result of subtracting b from a.
float subtract(float a, float b){
  return a-b;
}//end subtract

It's a bit verbose for a simple function but for more complex functions it is nice to have a summary of what is going on. The basics would be to describe each parameter and what the function returns. The end comment after the last curly bracket is nice when you have long, complex functions which may span oodles of lines in a text editor.

**Comment by joseph-allen** [comment]
for me a function called add, which takes two parameters is so trivial I would never comment any of it :P
I was taught to do the same, comment the start of any block and comment its end. When I moved to industry we were taught don't comment just write readable code instead.

Regardless the current comments are overkill, but I was expecting much less competent coders when I started this :)

**Comment by JimmySticks2001** [comment]
I agree that my above example is a bit much. There is more commentary than actual code. Perhaps we can save verbose commentary for more complex things. I can go ahead and push a commit that removes the current "Issue #" comments.

**Comment by joseph-allen** [comment]
sure, this is more here despite being a trivial task as an opportunity for somebody to learn Git :)

**Comment by JimmySticks2001** [comment]
Good! I need practice. I have only used Git to track my own progress on projects, never collaborating with others. Changing the code will be the easy part. Not wrecking your master branch or pushing old code will be the tricky part for me. I need to learn the best practices for collaborative git usage.

**Comment by joseph-allen** [comment]
luckily pull requests kind of make it okay, and quite difficult to really really screw anything up 💃

**Comment by WookiefromNZ** [comment]
I removed comments and the setup draw functions when i was working on the division, so it was less cluttered. Should i have just put the division code in and not removed other stuff?

Im OCD and irregular spacing/messy comments get to me lol.
