### ISSUE TITLE
Cant use this?

### ISSUE THREAD

**Issue by WookiefromNZ** [joezcool02/OurCalculator#27]
I have no idea what i am doing here. What is a pull request, what is merge. How do i get the code so i can change it how do I then post it back? Am i just expected to know this stuff? The tutorial was beyond me.

**Comment by GideonBuckwalter** [comment]
[This](https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/) tutorial? It was a little advanced.
Daniel Shiffman did a pretty good [set of videos](https://www.youtube.com/playlist?list=PLRqwX-V7Uu6ZF9C0YMKuns9sLDzK6zoiV) that were helpful to me. Hope this helps :)

**Comment by WookiefromNZ** [comment]
Thanks Ill check out Dan's videos. I can't seem to do anything other than comment. Yea that's very similar to the ones I've found

**Comment by WookiefromNZ** [comment]
Nah this seems beyond me. I just wanted to put up my code for the division but I can't figure it out. The tutorials either are too technical or jump all over the place. I just wanted a step by step. Good luck with the calculator anyway :)

**Comment by joseph-allen** [comment]
@WookiefromNZ don't worry. Merges are something I still have problems with years into industry, I will do it for you for now but never give up :)
