### ISSUE TITLE
issue 14: indent style

### ISSUE THREAD

**Issue by JornPrengerFormeel** [joezcool02/OurCalculator#30]
Hey!

An important thing of programming is to keep the code "clean" and consistent.
For this we use indent styles.
My question:"What indent style do you want to use"

Allman:
for(blablabla)
{
     line();
}

K&R:
for(blablabla){
     line();
}

**Comment by WookiefromNZ** [comment]
One vote for K&R, I like the opening curly bracket on the same line, less whitespace.

**Comment by joseph-allen** [comment]
good idea to agree consistency early on, big projects normally have a file called contributing or something which contains information like this on how to make a pull request and what styles to use!

**Comment by JornPrengerFormeel** [comment]
lets close this too

**Comment by joseph-allen** [comment]
this was more of an ongoing discussion than an issue so I agree :) 
Generally just try to persist whatever styles you find in the code so far
