### ISSUE TITLE
issue 15: button layout

### ISSUE THREAD

**Issue by JornPrengerFormeel** [joezcool02/OurCalculator#32]
I'm doing this like this, but if i will add more and more buttons the code will be very long.
any ideas to make more buttons but keep it short

int w = 50;
int h = 50;
int x = 50;
int y = 50;

void setup()
{
  size(600,600);
}

void draw()
{
  buttons();
}

void buttons()
{ 
  rect(w,h,x,y);
  if(mouseX >= w && mouseY <= w + x && mouseY >= h && mouseY <= h + y & mousePressed)
  {
     fill(0);
  }
}

**Comment by JornPrengerFormeel** [comment]
I think this needs to be done with arays?

**Comment by joseph-allen** [comment]
you could pass the arrays but this is something we could in future move to a separate file GUI.pde.
For the ticket just get it working, we can clean it up next :)
