### ISSUE TITLE
Issue 16: Calculation input method

### ISSUE THREAD

**Issue by JimmySticks2001** [joezcool02/OurCalculator#36]
I think decisions need to be made about how our calculator will operate. There are [several methods](https://en.wikipedia.org/wiki/Calculator_input_methods) of calculator input to choose from. Chain calculation, infix, and postfix are some of the options. I would vote for chain calculation (the algebraic entry system) where the previously entered equation is calculated upon pressing of another operation. I think it would be the most simple to program and is the most widely understood calculator input method.

**Comment by joseph-allen** [comment]
looks good to me, the task here I guess should be to build this string from key presses. Again this is blocked for now until the basic layout is made

**Comment by JornPrengerFormeel** [comment]
will we have ( and ) function for example

4(5-5+3)

this will be 20-20+12=12

**Comment by JornPrengerFormeel** [comment]
or (4+3)(2+1) this will be 8 + 4 + 6 + 3

**Comment by ayush-seth** [comment]
I think we should go for infix, infact that's what is currently implemented and that's how human read expressions

**Comment by ayush-seth** [comment]
This will be closed for now, unless we decide to change input method in future since this is already resolved.
