### ISSUE TITLE
issue 17: label all the buttons

### ISSUE THREAD

**Issue by JornPrengerFormeel** [joezcool02/OurCalculator#38]
We need to label the buttons 1, 2, 3 etc and ofcourse x, -, +, /

**Comment by hschallh** [comment]
@jorn600 The label is the third argument in the constructor for the button class. Try changing `Button twobutton = new Button(100, 200, "1");` to `Button twobutton = new Button(100, 200, "2");`

**Comment by GideonBuckwalter** [comment]
Hey, I'll do this and put the buttons in the `buttons` ArrayList as well.

**Comment by JornPrengerFormeel** [comment]
cool!
