### ISSUE TITLE
Don't forget to call out that you are working on something! 

### ISSUE THREAD

**Issue by joseph-allen** [joezcool02/OurCalculator#43]
Just had three people submit PRs for the same issue, let's stop that from happening.

On the right hand side you can see "Assignees" you should be able to assign yourself to a task there. If not let me know

**Comment by joseph-allen** [comment]
test it out here if you like :)

**Comment by ayush-seth** [comment]
I think only owners can assign people to issues, we can't assign ourselves, so you will have to assign people to issues.

**Comment by joseph-allen** [comment]
you are correct, I wasn't sure where the limitations lied. A comment will do then :)

**Comment by ayush-seth** [comment]
People can comment and then you can assign that person to that particular issue so it will be clear to others

**Comment by joseph-allen** [comment]
of course
