### ISSUE TITLE
issue 17: * and clear on the bottom

### ISSUE THREAD

**Issue by JornPrengerFormeel** [joezcool02/OurCalculator#45]
please make the * sign and the clear sign on the bottom

**Comment by jorn600** [comment]
ill work on this

**Comment by ayush-seth** [comment]
Let's not worry about such aesthetics first and get the basic functionality working? We can polish the looks anytime

**Comment by joseph-allen** [comment]
agreed, this is a design choice for now. we can do one big design revamp later :)

closing this for now unless somebody wants to reopen it :)

**Comment by JornPrengerFormeel** [comment]
oke, sorry

**Comment by joseph-allen** [comment]
no need to apologies it's open source. If people agree it's a priority it will become one :)

**Comment by joseph-allen** [comment]
The worst thing you can do is say nothing!
