### ISSUE TITLE
Getting the user input

### ISSUE THREAD

**Issue by ayush-seth** [joezcool02/OurCalculator#46]
Before we decide, how to interpret the expression and calculate the result, we need to worry about how to get the user input.

There is no native method of getting a string from user in processing, so here are two ways we can go about this:

1. Using a processing GUI library called [controlP5](https://github.com/sojamo/controlp5) which has easy syntax and is very user friendly and easily customizable.

2. Using inbuilt [Java Swing classes](https://docs.oracle.com/javase/tutorial/uiswing/components/textarea.html) which are way more complex than using controlP5 but have the plus point of being native to Java.

Personally I will suggest that we use [controlP5](https://github.com/sojamo/controlp5)

**Comment by hschallh** [comment]
Is a mouse press over a button not considered user input?

**Comment by ayush-seth** [comment]
Oh, you are right @hschallh , I don't know what I was thinking, perhaps we could save this for later, to let the user type instead of forcing them to click, like a typical calculator works on a desktop

**Comment by JornPrengerFormeel** [comment]
We can probably do this without controlp5

**Comment by hschallh** [comment]
Definitely a next step.

**Comment by hschallh** [comment]
@jorn600 is right, we could implement this with [keyPressed()](https://processing.org/reference/keyPressed_.html)

**Comment by ayush-seth** [comment]
@hschallh that will be way more complex, we will have to listen to every key press, and then concat each character and build a string from that, also how do you know that the user has finished entering and that you can compute the expression now? This will be much less complicated with controlP5, where we can just create a text area with a submit button

**Comment by hschallh** [comment]
We would treat each key press as a button press and compute answers in the exact same way we compute answers from using the GUI.

**Comment by hschallh** [comment]
But, like you said, something to save for later.

**Comment by ayush-seth** [comment]
Alright, I'll close this one now and open a new one to build the expression string from button presses.
