### ISSUE TITLE
Issue 17: Update Git Attributes

### ISSUE THREAD

**Issue by joseph-allen** [joezcool02/OurCalculator#49]
[Line Space](https://help.github.com/articles/dealing-with-line-endings/#per-repository-settings)

mac and windows use different line spacing which is bad!

**Comment by FreedomGrenade** [comment]
[https://help.github.com/articles/dealing-with-line-endings/](Is this helpful?)

**Comment by ayush-seth** [comment]
#53 fixes this hopefully

**Comment by ayush-seth** [comment]
Additional steps, everyone on a windows system, please do the following-

Open up cmd and type, `git config --global core.autocrlf`, if nothing shows up then do the following-

`git config --global core.autocrlf true`

After doing that, make sure it worked by typing `git config --global core.autocrlf` again and you should see `true` being written out.

More info can be found [here](http://adaptivepatchwork.com/2012/03/01/mind-the-end-of-your-line/)

**Comment by joseph-allen** [comment]
Issue resolved but everybody should do the above steps
