### ISSUE TITLE
Issue 18: Evaluating Expression

### ISSUE THREAD

**Issue by joseph-allen** [joezcool02/OurCalculator#50]
Evaluate the expression of the current sum

**Comment by joseph-allen** [comment]
@MasterYushi working on this

**Comment by ayush-seth** [comment]
Can you assign in to me also, like you self-assigned this? It'll be helpful to see the results of that since I am learning git

**Comment by joseph-allen** [comment]
it won't let me for now but I swear I saw it happen earlier? my internet is being really slow today so the hot search isn't doing anything

**Comment by ayush-seth** [comment]
You can try adding me as a collaborator in your repo settings, but that will give me push access to the repo so I'm not sure about what to do here.

Update: Apparently, you can't assign issues to non-collaborators, but it seems to be a requested feature.
This is what I found : https://github.com/isaacs/github/issues/100

**Comment by joseph-allen** [comment]
I wonder how other large projects do it? From the ones I have worked on people just make pull requests and comment them in the issue

**Comment by ayush-seth** [comment]
That's just a work around I guess

**Comment by joseph-allen** [comment]
it is just because I don't want to close requests because somebody already did them. But I suppose we will have to deal with it :)

**Comment by ayush-seth** [comment]
Okay, I did my research on this and this one is the toughest part of making a calculator, since java is a compiled language, String expressions can't be evaluated as actual code, so the easiest solution is out of the window. This leaves us with the following two ways to deal with - 

1. Use a library, like [JEL](http://www.gnu.org/software/jel/) 
>JEL is the library for evaluating a simple single line expressions in Java. he key feature of JEL is the fact that it is a compiler ! To write the interpreter for expressions is the task, close to trivial but incurs a HUGE perfomance penalty due to the fact that Java is interpreted language itself. JEL, in contrary, compiles expressions directly to Java bytecodes, allowing their fast evaluation. Moreover, if user's Java virtual mashine has JIT compiler, expressions are transparently compiled into the native machine code, resulting in performance HIGHER that for most C written interpreters (plus JEL do not require recompilation when transferred from platform to platform).

2. Using the `eval()` function by importing the ScriptEngine class and processing the `expression` string as a piece of javascript code. This option, obviously has some issues - Loading an entire JavaScript interpreter to do some math seems like a huge waste. Morever this opens upto major security issues, which we can leave for future but still I thought it should be mentioned.

So, for me the obvious choice is using JEL to compute expression, what do you guys think?
@joezcool02 @GideonBuckwalter @hschallh

**Comment by joseph-allen** [comment]
could we not do something a little more simple like have a number always availible in the store which creates a new string?

press 1 puts 1 in the store.
press 1 again multiples the store by ten and adds one giving 11.

this way we aren't working in strings?

or even have a button that lets us swap which store we are working in?

I would rather the calculator still be in our control than conventional just for learning reasons

**Comment by hschallh** [comment]
@joezcool02 I agree. I don't think we need to over complicate things.  If we are doing an immediate execution calculator, there is no need to evaluate strings.

**Comment by ayush-seth** [comment]
We will over complicate things by building an immediate expression calculator, we will have to build our own lexer and parser from scratch. Moreover, immediate expression calculator will not take precendence order into account which is not always the desired result, moreover, the `=` button will just be useless then if we evaluate the expression at every button press

**Comment by ayush-seth** [comment]
On the contrary, using the ScriptEngine parser would look something like this:

```
ScriptEngineManager manager = new ScriptEngineManager();
ScriptEngine engine = manager.getEngineByName("js");
Object result = engine.eval("4*5");
```

Instead of `"4*5"`, we just pass the the `expression` string and that's it. Surely, this is the least complicated it can get.

**Comment by joseph-allen** [comment]
okay let's go with this. My only concerns were that we wouldn't have enough to do but I realize when this is done we can just start the next project anyway :)

**Comment by joseph-allen** [comment]
@MasterYushi I can make you an owner of this repo as well if you are interested in trying out the ownership side of things? Then you will be able to merge as well

**Comment by ayush-seth** [comment]
@joezcool02 Sure!

**Comment by ayush-seth** [comment]
I am not suggesting this to be the end of this project, but to start with something simple like this and at least get a working prototype out there that people can use, as this project grows, we can then start building out our own lexer and parser.

**Comment by joseph-allen** [comment]
of course!

**Comment by ayush-seth** [comment]
This has been implemented now in the new `eval` branch so I'll close this one.
