### ISSUE TITLE
New GUI class

### ISSUE THREAD

**Issue by ayush-seth** [joezcool02/OurCalculator#54]
I have an idea to create a new GUI class for the whole button thing to clean up the main sketch, so you can just say something like `gui.generate()` in the main sketch to make it work. Should this be implemented? 

In the long term, this could open up creating multiple gui's and even multiple calculators.

**Comment by joseph-allen** [comment]
I think it is worthwhile even just to clean up the main sketch.

In my mind math functions shouldn't be in the main sketch either!

**Comment by ayush-seth** [comment]
As of now we don't need the maths functions for anything since we will be using JEL/ScriptEngine whichever is decided upon

**Comment by ayush-seth** [comment]
All the proposed changes are in the new branch gui, when it is deemed final, it will be merged with the master branch, leave your comments/suggestions here about improvements or submit a PR yourself to [`gui branch`](https://github.com/joezcool02/OurCalculator/tree/gui)

**Comment by GideonBuckwalter** [comment]
Looks great!

**Comment by GideonBuckwalter** [comment]
Are we planning on keeping these two branches separate, or will they be merged soon? I just want to know if I should be working off of the `gui` branch or `master`.

**Comment by ayush-seth** [comment]
This will be merged as soon as the gui changes are confirmed final, if you want to improve the gui, or work on something related to gui, commit on gui branch, if it is completely something else then commit on master. 

The point of this branch is to keep gui seperate until it is perfected, which it is not currently. 

One thing you could work on is adding a del button that will delete the last character entered.

**Comment by GideonBuckwalter** [comment]
Ok, well I'd like to retry adding the button flashing behavior I was working on. Is that too unrelated for the `gui` branch? If so, I'll probably have to wait until your branch is merged because my changes – if written for the `master` branch – will probably conflict with `gui`.

**Comment by ayush-seth** [comment]
If that requires editing only the button class, you can do so in either of the branches, if you will need to do some other changes, I would suggest you do it in the gui branch since buttons are a part of gui

**Comment by joseph-allen** [comment]
I would say things like the delete button are there own seperate issue. Just get a GUI in asap :)

**Comment by ayush-seth** [comment]
@joezcool02 We already have a working gui

**Comment by joseph-allen** [comment]
oh yeah, whoops!

**Comment by ayush-seth** [comment]
The gui branch is merged with master now
