### ISSUE TITLE
Issue 19: Minor fixes

### ISSUE THREAD

**Issue by FreedomGrenade** [joezcool02/OurCalculator#58]
- [x] Add brackets and decimal - I think this might be as simple as adding buttons, at the moment I can't think of any reason an invalid bracket syntax would pass to the display.  
- [x] Calculator division:  Division returns a float, and often it's too big for the display.   
An easy fix for this is to recast it, but maybe increase display? or Shrink text?
`gui.expression.append((answer instanceof Double)?((Double)answer).floatValue():answer);`

- [x] Calculator appends new input to the Old:   ie sequence  5.+.5.=.1.2    = 1012

**Comment by ayush-seth** [comment]
Brackets and decimal will be added soon, keep one issue for a single topic/problem.

This bug can be fixed easily, we can round of the final answer to a specific number of decimal places, we need to decide first how many decimal places to keep and then I can fix it.

**Comment by FreedomGrenade** [comment]
But I really wanted to use the tags.

**Comment by ayush-seth** [comment]
What tags?

**Comment by ayush-seth** [comment]
@joezcool02 What do you think, should the decimal places be fixed to two?

**Comment by joseph-allen** [comment]
I feel like we should just go as precise as Java lets floats go anyway? But I haven't really looked into how the calculator works

**Comment by ayush-seth** [comment]
@joezcool02 I am going to commit a delete button, decimal button and parentheses just now, you can pull and check it yourself

**Comment by joseph-allen** [comment]
will do @MasterYushi

**Comment by joseph-allen** [comment]
again things like this need Issues as well in my opinion

**Comment by ayush-seth** [comment]
@joezcool02 I have the commit ready to be pushed, we can create a new issue for features: decimal, delete and parentheses buttons.

This issue already mentions these problems though

**Comment by joseph-allen** [comment]
oh yes, this issue is named too ambiguously.
make a PR and I will merge it :)

**Comment by ayush-seth** [comment]
@joezcool02 I am not sure if you are aware that since I have push rights to this repo now, anything I push from my local clone will directly be commited, that's why I am using branches for my new commits, which will be merged into master whenever decided.

**Comment by joseph-allen** [comment]
you can still fork it yourself I believe to keep the process the same? I may be wrong I have never done it

**Comment by ayush-seth** [comment]
Yes I can but I deleted the fork since keeping it synced is a nuisance and introduces new unwanted "merge" commits which makes it messy. So I just cloned this one directly.

So far, I've been creating new branches for big commits and pushing the small ones directly, this one a small one which just adds a few lines so I was going to commit it directly into `eval` branch but now that I think about it I guess this should go into master

**Comment by FreedomGrenade** [comment]
@MasterYushi  by tags I just mean the task list markdown.

**Comment by ayush-seth** [comment]
We can keep it that way, one of them has been fixed. What do you mean by *Calculator appends new input to the Old: ie sequence 5.+.5.=.1.2 = 1012*? Can you be a little more elaborate?

**Comment by FreedomGrenade** [comment]
@MasterYushi 

Entering 5+5=   leaves an answer of 10 in the display.    
Any further button presses treat the 10 as if the user just entered it as 1, 0
The makes sense with operators, but with other numbers It seems wonky.   
I mean, I don't think it's a big deal, but regular physical calculators usually clear the input if a new expression is being entered.

**Comment by ayush-seth** [comment]
Yes, that happens currently, so you want the answer to be cleared on a new button press after = is pressed?

**Comment by FreedomGrenade** [comment]
Yea!, but just for numbers (and brackets i guess).  It's useful for operators.

**Comment by ayush-seth** [comment]
I don't get the operator thing, any valid input wouldn't end with an operator, it can only end with a number or a bracket

**Comment by FreedomGrenade** [comment]
I mean the button pressed after [=], just clear if it's a number or bracket

**Comment by ayush-seth** [comment]
That would create confusion if it clears sometimes and sometimes it doesn't, we should decide on one

**Comment by FreedomGrenade** [comment]
I don't know, Personally I think it makes sense.   
If there's an answer in the display and + is pressed I think its fair to assume they want to add the previous answer.
But if there's and answer, and a number or bracket is pressed then it represents a new expression.

**Comment by FreedomGrenade** [comment]
I mean do it one way or another, it can always be changed later.   
Fits the purpose of this whole project anyhow.   
Plus who knows, if we keep going, we might even completely change how buttons, calculator works.

**Comment by ayush-seth** [comment]
How the evaluation is done is very likely to change soon, because we are using a script engine right now which is not the most efficient but gets the work done. I'll see what I can do

**Comment by ayush-seth** [comment]
@joezcool02 Part 3 of this issue is fixed, I will be sending a PR soon, what should I do about part 2 of this issue? I want to fix it in the same PR so we can close this issue

**Comment by ayush-seth** [comment]
All of this is fixed in PR #66

**Comment by joseph-allen** [comment]
merged and done :)
