### ISSUE TITLE
multiply from floempie doenst work.

### ISSUE THREAD

**Issue by JornPrengerFormeel** [joezcool02/OurCalculator#6]
my add function then probably also doesnt work, i dont have processing on this pc right now

**Comment by joseph-allen** [comment]
so normally what we do here is this is considered a bug, standard practice is to put a thumbs up on the post/comment if you can duplicate it :)

**Comment by joseph-allen** [comment]
`float x = multiply(2,5);
print(x);`

in the setup function seems to work well for me! Can you replicate it @jorn600 ?

**Comment by JornPrengerFormeel** [comment]
O sorry, yes it works

**Comment by joseph-allen** [comment]
Closed!
