### ISSUE TITLE
Question about branches.

### ISSUE THREAD

**Issue by FreedomGrenade** [joezcool02/OurCalculator#63]
Ok so I understand that if you want to make changes you should make a new branch.
Now what I'm not sure about is when there is another branch with proposed changes, but you want to make additional changes to that branch should you make another 3rd 'feature' branch?  

Like with 'eval' should you create a branch called 'eval_add_blah_blah'?   

If so, how do those typically get merged.   Would you merge 'eval'->'master'  then over top of that merge 'eval_add...', or merge 'eval_add..' -> 'eval' and then onto 'master'?

**Comment by joseph-allen** [comment]
it depends I suppose?

if you were going to make two features you would branch off master with:
master -> feature_1
master -> feature_2

then if you wanted to fix a bug on feature_1 I would just say make another commit on the feature_1 branch.

We would then merge the feature_1 branch into master which would have both the original commit and the bugfix included. Is that answering your question?

**Comment by ayush-seth** [comment]
if you want to add to a branch on the main project, make a branch off the branch you want to add to in your fork and then do a PR to merge them.

Example, you want to add to eval, make a branch off eval in your fork, not off master.
