### ISSUE TITLE
Issue 3: User Interface

### ISSUE THREAD

**Issue by FreedomGrenade** [joezcool02/OurCalculator#8]
[Treverios](https://www.reddit.com/r/processing/comments/6cpcbj/ourprocessing_ourcalculator/dhwmbm4/)

 semi-suggested a GUI.  

Sorry if this is out of line, I just want to get used to using github.

**Comment by GideonBuckwalter** [comment]
Sounds good. Maybe someone could start by writing a button class/interface which responds to clicks by calling a function.

**Comment by joseph-allen** [comment]
@FreedomGrenade this is fine! 

The thing is this, in an open source project if somebody picks up this issue we have to create an entire GUI with no plans yet, also the GUI is a big undertaking.

@GideonBuckwalter commented as I wrote this and was exactly correct. Instead somebody should create an issue of a smaller, atomic piece of work.

go ahead and make an issue and let people know you are working on it :)

**Comment by JornPrengerFormeel** [comment]
i think a guy would be cool, gets more style then

**Comment by joseph-allen** [comment]
closing this as it is too generic for any one person to take right now
