### ISSUE TITLE
Issue 4: Answer State Variable

### ISSUE THREAD

**Issue by GideonBuckwalter** [joezcool02/OurCalculator#9]
So I'm thinking about how we're going to store the previous calculation. It would probably be enough to have a global floating-point variable called like `answer` or `prevAnswer`. Whenever a calculation is performed, the result would be stored in this variable, which can then be accessed when we need to draw the answer on the screen.

Eventually (to implement parentheses) it might be good to try making a stack of operations and operands (maybe using `String`s to hold representations of the data and functions), but it's probably too early for that.

**Comment by GideonBuckwalter** [comment]
P.S. Do we need to wait to be assigned things, or could I start working on this and submit an unsolicited pull request?

**Comment by joseph-allen** [comment]
just say you are working on it and go ahead :)

**Comment by joseph-allen** [comment]
I am using the 'help wanted' label for unassigned tasks

**Comment by JornPrengerFormeel** [comment]
We can Also not do this.

**Comment by joseph-allen** [comment]
Done!
